# Generated by Django 5.0.1 on 2024-08-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=255)),
                ('builtup_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_stage', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(default='images/projects/default.png', max_length=255, upload_to='images/projects')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['id'],
            },
        ),
    ]
