# Generated by Django 5.0.1 on 2024-09-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='passcode',
            field=models.IntegerField(default=1234),
        ),
    ]
