# Generated by Django 5.0.1 on 2024-09-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('running', 'Running'), ('completed', 'Completed')], default='not_started', max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_stage',
            field=models.CharField(choices=[('LOD1', 'Level of Development 1'), ('LOD2', 'Level of Development 2'), ('LOD3', 'Level of Development 3'), ('LOD4', 'Level of Development 4'), ('LOD5', 'Level of Development 5')], default='LOD1', max_length=10),
        ),
    ]
