# Generated by Django 5.0.1 on 2024-09-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_status_alter_project_project_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LOD1', 'Level of Development 1'), ('LOD2', 'Level of Development 2'), ('LOD3', 'Level of Development 3'), ('LOD4', 'Level of Development 4'), ('LOD5', 'Level of Development 5')], max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('running', 'Running'), ('completed', 'Completed')], max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_stage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='stages',
            field=models.ManyToManyField(related_name='projects', to='projects.stage'),
        ),
    ]
