# Generated by Django 5.0.1 on 2024-09-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_stage_remove_project_project_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stages',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.stage'),
        ),
    ]
