# Generated by Django 5.0.1 on 2024-09-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_stage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='images/projects/default.png', upload_to='images/projects'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(choices=[('LOD1', 'Level of Development 1'), ('LOD2', 'Level of Development 2'), ('LOD3', 'Level of Development 3'), ('LOD4', 'Level of Development 4'), ('LOD5', 'Level of Development 5')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=15),
        ),
    ]
