# Generated by Django 5.0.1 on 2024-09-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_image_alter_stage_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='stages',
        ),
        migrations.AddField(
            model_name='project',
            name='lod100_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=15),
        ),
        migrations.AddField(
            model_name='project',
            name='lod200_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=15),
        ),
        migrations.AddField(
            model_name='project',
            name='lod300_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=15),
        ),
        migrations.AddField(
            model_name='project',
            name='lod400_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=15),
        ),
        migrations.AddField(
            model_name='project',
            name='lod500_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=15),
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
