# Generated by Django 5.0.1 on 2024-01-28 16:59

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(default='images/blogs/doc.png', max_length=255, upload_to='images/blogs')),
                ('category', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('author_pic', models.ImageField(default='images/blogs/doc.png', max_length=255, upload_to='images/blogs')),
                ('published_date', models.DateField()),
                ('reading_time', models.CharField(max_length=20)),
                ('content', tinymce.models.HTMLField(default='')),
                ('tags', models.ManyToManyField(to='blogs.tag')),
            ],
            options={
                'verbose_name_plural': 'Blogsss',
                'ordering': ['id'],
            },
        ),
    ]
